export const APP_VERSION = "1.14.0";

// Each entry is an array of bullet points — one string per item.
// New versions should follow this same format.
export const CHANGELOG: Record<string, string[]> = {
  "1.14.0": [
    "Enhancement: CardModal fwd/back navigation in search context — Prev/Next chevron buttons navigate through the current results array; buttons hide when ≤1 result; keyboard arrow keys supported",
    "Enhancement: set code in CardModal Product Details is now clickable — blue text, underline on hover; clicking searches e:{setCode} and switches to search view from either context",
    "Enhancement: artist name in CardModal Product Details is now clickable — blue text, underline on hover; clicking searches a:\"artist name\" and switches to search view from either context; row hidden when no artist field is present",
    "Enhancement: sort direction toggle added to search toolbar — asc/desc arrow button mirrors deck view pattern; persists to localStorage (mtg-search-sort-direction); disabled at Relevance sort",
    "Filter defaults (pre-release): Price Any, Release Year All, format badge off by default; per-deck badge persistence (mtg-search-filter-active-{deckId}); Reset to defaults button in sidebar filter panel appears when any filter differs from defaults",
    "Bug fix: search loading spinner was invisible — border-t-tertiary is an unmapped token resolving to transparent; fixed to border-t-blue-400 (same fix as CardModal spinner in v1.13.0)",
    "Bug fix: autocomplete dropdown no longer opens when navigating via set/artist click — programmatic query changes set a suppressAutocompleteRef flag to skip the autocomplete effect for that cycle",
  ],
  "1.13.0": [
    "Bug fix: reversible card commander eligibility — Secret Lair display commanders (e.g. Atraxa, Praetors' Voice) failed the isEligibleCommander check because their type_line lives in card_faces[0] rather than the root; now falls back to card_faces[0].type_line and card_faces[0].oracle_text",
    "Bug fix: Swap Art variant picker was empty for reversible/Secret Lair cards — oracle_id lookup fails for these layouts; now uses name-based exact search (Scryfall !'name' syntax) for DFCs and oracle_id for standard cards",
    "Enhancement: Vehicle/Spacecraft commander support — July 2025 rules update; legendary Vehicles and Spacecraft with defined P/T are now eligible commanders",
    "Enhancement: crown badge tooltip now uses a styled hover div instead of a browser title attribute — eligible creature commanders show 'Set as Commander'; eligible Vehicle/Spacecraft commanders add a blue ⓘ info icon linking to the WotC Edge of Eternities mechanics article",
    "Enhancement: tooltip has a 150ms dismiss delay so the mouse can travel from the crown badge to the ⓘ link without the tooltip disappearing",
    "Chore: ScryfallCard type extended with optional power and toughness fields (string | undefined)",
    "Chore: isVehicleOrSpacecraftCommander helper exported from formatRules.ts for use in VisualCard and ListCardTable",
  ],
  "1.12.5": [
    "Bug fix: home button now works from the settings overlay — clicking navigates home and closes settings in both expanded and collapsed sidebar states",
    "Bug fix: home button no longer shows prohibition cursor when settings is open on the home screen — disabled state now only applies when actually viewing the home screen without settings",
    "Bug fix: home screen deck cover cards now show correct total card count (sum of quantities) instead of unique entry count",
    "Bug fix: clicking a deck name or sideboard icon in the Decks tab while settings is open now closes settings and navigates directly to the deck",
    "Settings overlay contract added to project notes: any navigation action (tab, deck, home) must call onCloseSettings to prevent the settings view from persisting silently",
  ],
  "1.12.4": [
    "Home screen: app loads to a welcome screen instead of an empty workspace on first visit or after navigating home — shows heading, rotating tagline, deck cover cards, and a ghost deck card to create a new deck",
    "Rotating taglines: 13 taglines chosen at random per session (sessionStorage-backed) — same tagline shown on refresh, new one each session",
    "Deck cover cards: each saved deck appears on the home screen with a deterministic gradient tint; click to open directly",
    "Ghost deck card (home screen): dashed card tile opens the format picker to create a new deck",
    "Ghost card in empty workspace: empty deck shows a dashed ghost tile in the card grid — click to trigger the search takeover",
    "Search takeover: empty-deck-aware search entry point — heading, autofocused input, quick-tag buttons (Ramp, Removal, Card Draw, etc.) — opens on Search tab when ghost card is clicked",
    "Sidebar 'New Deck' button replaced with a dashed ghost slot — same FormatPicker behaviour, quieter visual",
    "Home icon added to expanded sidebar footer (left of version badge) and collapsed rail (below Settings) — dimmed when already on home screen, navigates home when active",
    "Page title updated to 'TheBrewLab'",
    "useDeckManager: no auto-create deck on first load or last-deck delete — empty state now shows home screen instead of a blank Untitled deck",
  ],
  "1.12.3": [
    "Hotfix: renamed 'TheBrewLab' to 'The Brew Lab' throughout Settings Hub — header, About description, legal disclaimers, and Support tab copy",
    "About description updated: added project name, expanded purpose to include teaching and learning",
    "Team monogram updated: 'P' → 'PT' to represent Phi & Thurgood together",
  ],
  "1.12.2": [
    "Bug fix: sidebar tab bar restyled with seamless physical tab metaphor — active tab blends into sidebar body (bg-surface-panel, transparent bottom border); inactive tab recesses below it (bg-surface-deep, visible bottom edge); no blue underline indicator",
    "Inactive tab hover lifts background to match the sidebar surface and brightens text — matches the active state appearance without the full commit",
    "Collapse button (desktop) and mobile gear icon gain recessed background to match the tab row treatment",
    "Bug fix: search sort dropdown now works — selecting Name, Price ↑, Price ↓, Mana Value, or Color re-fetches results with the correct Scryfall order; Relevance omits the order clause for natural Scryfall ranking",
    "Sort default is Price ↓ (order:usd) — preserves the existing priced-printing preference",
    "Price rescue on card add still uses order:usd internally regardless of selected sort",
  ],
  "1.12.1": [
    "Search toolbar rows now match the deck toolbar's height rhythm — the divider lands at the same Y position when switching tabs, no layout hitch",
    "Search bar taller: inner container raised from 32px to 40px minimum height to fill the matched Row 1",
    "Search Row 2 controls grouped into a single pill container matching the deck toolbar's outlined button-group style — sort, tile size, and view toggles unified",
  ],
  "1.12.0": [
    "Settings Hub: full workspace-takeover settings view replaces the sidebar footer accordions — opens from the version badge, collapsed rail gear icon, or mobile gear in the tab bar",
    "Preferences tab: Card Preview toggle (existing) and Theme picker — select Warm Stone or Zed Dark; persists to localStorage, applies with no flash on page load",
    "What's New tab: last 5 changelog versions with blue pill badge on current version",
    "About tab: project intro, Team (Phi & Thurgood Nguyen, Claude · Anthropic), Powered By (Scryfall, Next.js + Vercel, Tailwind CSS), and Legal disclaimers",
    "Support tab: Buy Me a Coffee and GitHub external links",
    "Sidebar footer simplified to version badge only — clicking opens What's New tab; coffee icon and gear icon removed from expanded footer",
    "Collapsed rail gear icon now opens the settings hub (Preferences tab) directly — sidebar stays collapsed",
    "Mobile gear icon added to sidebar tab bar; settings closes automatically when Search or Decks tab is clicked",
  ],
  "1.11.1": [
    "Focus ring color muted: --input-edge-focus and --border-line-focus changed from #c07a50 (bright copper) to #a0725c (darker, less visually heavy) in the Warm Stone palette — Zed Dark focus ring (#528bff) unchanged",
  ],
  "1.11.0": [
    "Dual-palette theme system: Warm Stone (default) with brown undertones and copper accents, plus Zed Dark alt-theme with blue-gray tones and blue accents — switch via data-theme attribute on <html>, no UI toggle yet",
    "Token count expanded from 12 to 25: added sidebar panel surfaces (bg-surface-panel, bg-surface-panel-raised, border-line-panel), input field tokens (bg-input-surface, border-input-edge, border-input-edge-focus, text-input-value, text-input-placeholder), focus/hover borders (border-line-focus, border-line-hover), and resolved flagged classes (text-content-disabled, bg-surface-deep, bg-surface-hover)",
    "Sidebar panel depth: Warm Stone sidebar is raised (lighter than workspace), Zed Dark sidebar is recessed (darker than workspace) — same token names, different visual hierarchy per theme",
    "All v1.10.0 flagged mid-tone classes resolved: text-neutral-700 → text-content-disabled, bg-neutral-950 → bg-surface-deep, hover:bg-neutral-600 → hover:bg-surface-hover, border-neutral-600 → border-line-hover, focus-within:border-neutral-600 → focus-within:border-input-edge-focus",
    "Input fields use dedicated raised tokens across search bar, filter panel, workspace toolbar name input, and import modal — inputs sit above their parent surface in both themes",
  ],
  "1.10.0": [
    "Design token system: 12 semantic CSS custom properties defined in globals.css and registered via Tailwind v4 @theme inline — surfaces (bg-surface-base/raised/overlay/backdrop), text (text-content-primary/heading/secondary/tertiary/muted/faint), and borders (border-line-default/line-subtle)",
    "All hardcoded neutral color classes replaced with token utilities across 17 files — changing a theme color now requires editing one place in globals.css",
    "Token naming rule: @theme inline --color-X generates utility [prefix]-X — text tokens use --color-content-* and border tokens use --color-line-* to avoid the doubled-prefix trap (--color-text-* would generate text-text-*, --color-border-* would generate border-border-*)",
    "Opacity variants (e.g. bg-neutral-800/50) and mid-tone flagged classes (text-neutral-700, bg-neutral-950, border-neutral-600, hover:bg-neutral-600) intentionally left as raw Tailwind — no token mapping needed for contextual states",
  ],
  "1.9.0": [
    "Release year filter: dual text inputs (year from / to) in the sidebar filter panel with three quick-select presets — This Year, Last 5 Yrs (default), and All; filter is active by default showing only the past 5 years",
    "Year syntax: injects year>= and year<= Scryfall clauses only when the range is meaningfully constrained (yearMin > 1993 or yearMax < current year); All preset produces no syntax",
    "CardModal Product Details: Released date row added below Price, showing the printing's release date (YYYY-MM-DD) from Scryfall",
    "Year filter persists to localStorage via the existing mtg-sidebar-filters key — survives page refresh and tab switches; old saved state without year fields falls back to defaults gracefully",
  ],
  "1.8.4": [
    "Bug fix: resolved hydration mismatch from filter persistence — server now always renders with default filters; stored values are applied after mount, matching the tile size pattern",
  ],
  "1.8.3": [
    "Tile size slider thumb restyled to match the price slider — white fill, blue border, neutral drop shadow; stop dots unchanged",
    "Price slider thumb now shows grab/grabbing cursor during drag",
    "Filter state (price, rarities, types, colors) now persists to localStorage and restores on page refresh — no more losing your filter settings after a refresh",
  ],
  "1.8.2": [
    "Bug fix: price filter default $100 ceiling now correctly filters out cards over $100 — removed an incorrect guard that skipped the usd<= clause at the default value",
    "Price inputs now auto-select on focus and accept free-form editing — the $ sign is a static label, validation is deferred to blur/Enter so intermediate values like empty or partial numbers are allowed",
    "Price range slider replaced with a drag-to-set control — includes a drag dot at the max position, live numeric feedback in the max input during drag, and commits on mouse release",
  ],
  "1.8.1": [
    "Bug fix: deck name input no longer shifts or jitters when renaming — replaced JS width measurement with CSS field-sizing: content for native auto-sizing with no double-render",
  ],
  "1.8.0": [
    "Tile size snap slider: new toolbar control in both deck and search views — 5 presets (XS/S/M/L/XL) via a vertical popover slider with drag-to-snap, click-to-jump, and card-shape visual hints",
    "Unified grid sizing: deck grid and search grid now share the same tile size config (gridConfig.ts) and the same localStorage key (mtg-tile-size) — changing size in one view persists to the other",
    "Grid column count at M (default): ~8 columns at 1680px effective width (1920px − sidebar − padding); XS reaches ~12 columns, XL drops to ~4 for large art view",
  ],
  "1.7.0": [
    "Bug fix: Planeswalker commander eligibility — Legendary alone no longer qualifies; must be Legendary Creature or have 'can be your commander' in oracle text",
    "Natural language set search: type 'jaws secret lair' or 'The Brothers War' to search cards from that set — fuzzy-matches against all Scryfall sets with a 'Set: [name]' chip shown in results",
    "set:CODE NLP token: direct passthrough for users who know set codes (e.g. 'set:BRO')",
    "Discard archetype NLP token: typing 'discard' maps to o:\"discard\" in search",
    "CardModal search context: modal stays open after '+ Add to Deck' and returns to Details tab instead of closing",
    "Group by type — commander group: designated commander card floats to its own top group when 'Group by Type' is enabled",
    "CardModal Swap Art tab: loading spinner while printings are fetching",
    "In-deck green dot tooltip: hovering the dot shows 'Already in deck'",
    "Filter All/None toggle: one-click select/deselect all for Rarity, Card Type, and Colors filter groups",
    "Color filter chip tints: active chips match their mana color (W stone, U blue, B dark, R red, G green, C gray)",
    "Price 'Any' toggle: disables the price ceiling filter entirely; slider dims when Any is active",
  ],
  "1.6.0": [
    "Search overhaul: two-tab app architecture — Search tab opens a full-width card grid workspace, Decks tab shows the deck builder; state persists across tab switches",
    "NLP search parser: natural language queries like \"black flying creatures under $2\" or \"ramp\" translate to structured Scryfall syntax; matched tokens shown as removable chips inline in the search bar",
    "Context-aware filter badge: auto-filters by active deck's format legality and commander color identity; format-specific badge colors (Commander gold, Standard blue, Freeform neutral)",
    "Autocomplete dropdown: Scryfall card name suggestions appear after 2 characters; cards already in the active deck show a green dot; Escape or Enter closes the dropdown",
    "Category chips: format-relevant quick-search shortcuts in the sidebar (Ramp, Removal, Card Draw, Wipes, Tokens, Creatures, Counters, Tutors, Lands, Burn) — filtered by active deck's format",
    "Sidebar filter controls: price range slider, rarity toggles, card type toggles, color toggles with mana pip icons — all combine into the live Scryfall query",
    "Search results in-deck indicator: cards already in the active deck show a green dot and 40% opacity dim",
    "CardModal context: opened from search shows '+ Add to Deck' button (adds current or variant printing); opened from deck view shows 'Confirm Art Swap' (unchanged)",
    "Toast feedback on add: shows 'Added {name} to {deck}'; duplicate adds show '(×N)' count",
  ],
  "1.5.4": [
    "Delete Deck and Delete Sideboard in the sidebar dropdown no longer show a second confirmation dialog — clicking the action executes immediately",
    "Owned −/+ increment buttons added to list view alongside the X/Y owned display — hover-visible, matching the qty button pattern",
    "Owned −/+ increment buttons added to grid view hover overlay — flanking the owned counter in the slide-up panel",
    "List view hover performance improved: mouse movement no longer triggers full Workspace re-renders — tooltip repositions via direct DOM update instead of setState",
  ],
  "1.5.3": [
    "Warning colors unified across grid and list view: format violation warning bar and qty pill badge are now red; list view warning triangle icon is red to match",
    "Qty number color logic simplified: green when fully owned, red when over copy limit, gray otherwise — at-copy-limit no longer changes qty color",
  ],
  "1.5.2": [
    "Workspace toolbar split into two rows: deck name + format badge on row 1, stats and controls on row 2 — eliminates name truncation and button crowding on long deck names",
    "Deck name input grows and shrinks to exact text width using a hidden measurer span — format badge sits immediately after the last character with no visible gap",
    "Deck name size increased to text-3xl for visual emphasis",
    "Grid view gap increased from gap-3 to gap-x-5 gap-y-7 — prevents qty pill and crown badge from overhanging into adjacent cards",
  ],
  "1.5.1": [
    "Grid view warning redesigned: corner triangle badge removed; amber warning bar now appears inside the hover overlay above qty controls — clearly scoped to the card",
    "Color identity warning text simplified: removes abstract mana symbol notation (e.g. 'has {G}') from the warning message",
  ],
  "1.5.0": [
    "FormatPicker popover now opens downward when there's more room below the trigger, and upward when near the bottom — applies to all three trigger points (+ New Deck, sidebar badge, toolbar badge)",
    "Collapsed sidebar rail + icon now opens FormatPicker popover to the right instead of immediately creating a deck — deck only created after format selection; Escape or click-outside cancels",
    "Commander eligibility check hardened to a full block — non-legendary cards (no 'Legendary' in type_line and no 'can be your commander' in oracle_text) cannot be designated as commander; click is a no-op in both list and grid view",
    "Grid view crown badge is now the sole commander toggle — replaces the 'Set as Commander' / 'Commander ✓' button that lived in the hover overlay",
    "Commander format: all non-commander cards show a dim gray crown on card hover; eligible (legendary) cards light up gold on crown hover with pointer cursor; ineligible cards stay dim with not-allowed cursor",
    "Active commander crown is always visible, solid yellow circle, scales on hover; clicking deselects commander",
    "Persistent qty pill badge added to every grid tile — circular badge at bottom center straddling the card edge; green when fully owned, amber when at copy-limit warning, neutral otherwise; fades out when hover overlay slides up",
  ],
  "1.4.1": [
    "Warning badge redesigned: filled amber triangle (raw SVG) replaces amber circle — no stroke outline, white ! line and dot as separate paths",
    "Warning badge repositioned to top-right corner in grid view (was top-left, stacked below crown)",
    "Crown badge stays alone at top-left in grid view — no more flex-col wrapper",
    "Crown SVG bumped from 16×16 to 18×18 inside the w-7 h-7 badge circle",
    "× remove button moved inset to top-right of card art (top-1.5 right-1.5, clipped by rounded-xl) — was straddling the corner edge",
    "List view warning icon updated to matching raw SVG triangle (16×16)",
  ],
  "1.4.0": [
    "Per-deck format: Freeform, Standard, Commander — centralized rules engine (formatRules.ts)",
    "Commander designation: crown badge in grid, crown icon in list, pinned to top in both views",
    "Color identity validation, singleton enforcement, and format-aware copy limit warnings",
    "Warning badges: filled amber circle with white ! on format violations — grid and list",
    "Format picker: accessible from sidebar badge, toolbar badge, and + New Deck button",
    "Format badges in sidebar: STD / CMD / FF — all clickable to switch format",
    "Format badge pill in toolbar: Standard / Commander / Freeform — clickable",
    "Sideboard-to-Commander dialog: merge or delete sideboard when switching to Commander",
    "Simulator: 5%/2% thresholds for Commander; commander excluded from library and Draw Odds",
    "List view: column reorder [−qty+][Owned][Name][Type][Mana][Price][×]; Owned simplified to X/Y",
    "Import/export: Format and Commander headers for round-trip fidelity",
  ],
  "1.3.2": [
    "Sideboard pricing: combined main+side total with (M+S) label in toolbar",
    "Deck name deduplication: auto-appends (2), (3), etc. on create and import conflicts",
    "Version badge: expands inline changelog instead of popup alert",
    "Collapsed sidebar rail: tooltips, click-to-expand, New Deck icon, PanelLeftOpen/PanelRightOpen toggle",
    "Card Kingdom button font size fixed so label fits on one line",
    "Qty badge removed from grid tile rest state — qty visible in hover overlay only",
  ],
  "1.3.1": [
    "Grid tile qty badge and × button now use solid backgrounds for readability",
    "Overlay qty number reflects green/red copy-limit color logic",
    "Deck name in toolbar truncates at 200px to prevent stats overflow",
    "Search results render styled mana cost symbols",
  ],
  "1.3.0": [
    "Collapsible sidebar with Search/Decks tab system — 48px icon rail when collapsed, smooth 300ms transition",
    "Deck management in sidebar Decks tab: sideboard controls, delete dropdown, import/export, buy links",
    "Workspace toolbar slimmed to single row",
    "Grid view: card art fills tile; hover reveals slide-up overlay with qty controls, owned counter, and × remove",
    "Inline mana cost symbols in search results",
    "Search field clear button with instant category snap-back",
  ],
  "1.2.1": [
    "Bug fix: land cards now appear in their own sort group when sorting by Color in list view",
  ],
  "1.2.0": [
    "Opening Hand Simulator: mana curve histogram (spells only, CMC 1–7+, normalized bars)",
    "Lands strip: count and percentage, static (does not update on draw)",
    "Draw Odds list: live next-draw probability per card with normalized bars and green/yellow/red thresholds",
    "Lands toggle in Draw Odds header",
    "Pin cards via Draw Odds row or card image — multiple pins, cleared on mulligan",
    "Mulligan counter in simulator header",
  ],
  "1.1.7": [
    "Bug fix: list view hover highlight restored as brightened tint",
    "Land rows now show tan/brown tint distinct from colorless gray",
    "Clicking a deck name in the dropdown keeps it open",
    "4-copy badge follows gray → green → red progression (green at 4, red at 5+)",
    "Unnamed decks show 'Untitled' in gray in the dropdown",
  ],
  "1.1.6": [
    "Deck dropdown radio buttons — click inactive deck to switch without closing",
    "Card count turns green at exactly 60 cards and red above 60",
    "4-copy warning badge changed from yellow to red",
    "Active Main/Side pill is now blue",
    "Deck name shows 'Untitled' placeholder when unnamed",
    "List view spacing between color and mana value sort groups",
  ],
  "1.1.5": [
    "Bug fix: blue dot in deck dropdown no longer closes the dropdown on click",
    "Card thumbnail toggle persists across page refreshes",
    "Owned counter supports inline typing in both grid and list view",
  ],
  "1.1.4": [
    "Grid view 4-copy warning tooltip now reads 'Exceeds 4-copy limit' (matching list view)",
    "Max-width cap added to all tooltips so long text wraps instead of clipping",
    "REVIEW.md session journal workflow introduced",
  ],
  "1.1.3": [
    "Shortened 4-copy warning text in list view",
    "Removed tooltip from X (remove) button in grid view",
    "Added 'Switch to main deck' / 'Switch to sideboard' tooltips to Main/Side pill",
  ],
  "1.1.2": [
    "4-copy tooltip renders below qty number to avoid clipping at scroll top",
    "Scroll container padding added so yellow highlight ring is fully visible on edge cards",
    "Removed Increase/Decrease tooltips from +/− qty buttons in grid view",
  ],
  "1.1.1": [
    "Hot fix: + on deck row activates deck, enables sideboard, switches to sideboard view, closes dropdown",
    "Sideboard view mode (main/sideboard) now persists across page refreshes",
    "Workspace overflow adjusted so tooltips and highlight rings are no longer clipped",
  ],
  "1.1.0": [
    "Sideboard support: enable a 15-card sideboard per deck from the deck dropdown",
    "Main/Side pill toggle in toolbar switches between views",
    "Search adds to sideboard when in sideboard view",
    "Import/export handles Sideboard section",
    "4-copy warning checks combined main + sideboard count",
    "UI persistence: grid/list, group-by-type, and last active deck restored on page refresh",
    "Sort direction toggle now has tooltip",
  ],
  "1.0.7": [
    "Inline quantity editing: click any qty number in grid or list view to type a new value",
    "Grid view − qty + controls grouped and centered",
    "Sort By dropdown (Original · Name · Color · Mana Value) with ↑↓ direction toggle",
    "Sort preference saved across sessions; sort controls also in Settings sidebar",
  ],
  "1.0.6": [
    "Owned quantity tracking: per-card ownedQty replaces boolean isOwned",
    "Grid and list views show ownership progress bar, gray overlay, and owned count",
    "Buy lists export only unowned copies",
    "Migrates old isOwned saves automatically",
  ],
  "1.0.5": [
    "4-copy soft warning badge in list view",
    "Buy buttons now exclude fully owned cards",
    "Swap art button always shows as active blue",
  ],
  "1.0.4": [
    "Refactor: extracted WorkspaceToolbar.tsx, DeckDropdown.tsx, and useDeckStats.ts — Workspace.tsx reduced from 607 to 333 lines",
  ],
  "1.0.3": [
    "Pricing fixes for $0.00 cards on add and import",
    "Full fidelity export/import with [SET] and [owned] tags",
    "Auto-scroll and yellow highlight ring on card add",
    "Themed dark scrollbars and settings menu with card preview toggle",
  ],
  "1.0.2": [
    "Collapsible footer, deck name dropdown, type column in list view, toolbar layout",
    "Owned card green tint, WotC disclaimer, 60-card highlight, and more",
  ],
  "1.0.1": [
    "Bug fixes: inline mana symbols, pricing improvements, card modal enhancements, set names, flavor text, and UI polish",
  ],
  "1.0.0": [
    "Initial Release: Visual Deck Builder, Goldfish Simulator, and Art Swapping",
  ],
};

export const CURRENT_CHANGELOG = CHANGELOG[APP_VERSION];
